spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: rpb_vts14
            client-secret: Rt0cnF8XptsvPkrh8fd8JbVIB4cALF6V
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.1.61:8085/rpb/login/oauth2/code/{registrationId}"

        provider:
          custom:
            authorization-uri: http://192.168.1.61:8888/realms/DRDO_DUMMY/protocol/openid-connect/auth
            token-uri: http://192.168.1.61:8888/realms/DRDO_DUMMY/protocol/openid-connect/token
            user-info-uri: http://192.168.1.61:8888/realms/DRDO_DUMMY/protocol/openid-connect/userinfo
            jwk-set-uri: http://192.168.1.61:8888/realms/DRDO_DUMMY/protocol/openid-connect/certs
            user-name-attribute: preferred_username

  thymeleaf:
    enabled: false
    cache: false

  mvc:
    view:
      prefix: /view/
      suffix: .jsp

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.session: DEBUG
    
server:
  port: 8085
  servlet:
    context-path: /rpb
session:
  cookie:
    same-site: none
    secure: false
   

rpbLogOut: http://192.168.1.61:8888/realms/DRDO_DUMMY/protocol/openid-connect/logout?client_id=rpb_vts14&post_logout_redirect_uri=http://192.168.1.61:8085/rpb


LabCode: DEBEL
ApplicationFilesDrive: D:\\IBAS\\   # windows D:\\IBAS\\      Ubuntu /opt/IBAS/ 
Attach_File_Size: 50

#headerLogo
headerLogo: "DRDO_DUMMY.png"

#image
image: "vedts.png"

MdmDb : pms_dms_dev  #pms_dms_dev

passwordChange : http://192.168.1.61:8888/realms/DRDO_DUMMY/login-actions/reset-credentials

app:
  datasource:
    mysql:
      username: root
      password: admin      
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.61:3307/rpb_test   #192.168.1.70:3306/ibas_3
      